INSERT INTO TypesOfAcademicWorkload (code,nameOfWorkload)
VALUES (1, 'лекция')
INSERT INTO TypesOfAcademicWorkload (code,nameOfWorkload)
VALUES (2, 'СРСП')
INSERT INTO TypesOfAcademicWorkload (code,nameOfWorkload)
VALUES (3, 'практ. занятие')
INSERT INTO TypesOfAcademicWorkload (code,nameOfWorkload)
VALUES (4, 'лаб. раб.')
INSERT INTO TypesOfAcademicWorkload (code,nameOfWorkload)
VALUES (5, 'КП')
INSERT INTO TypesOfAcademicWorkload (code,nameOfWorkload)
VALUES (6, 'дипломир. практика')
INSERT INTO TypesOfAcademicWorkload (code,nameOfWorkload)
VALUES (7, 'уч. практика')
INSERT INTO TypesOfAcademicWorkload (code,nameOfWorkload)
VALUES (8, 'экзамен')