INSERT INTO Discipline(ID,nameDiscipline,semester)
VALUES( 1,'ИКТ' ,1 )
INSERT INTO Discipline(ID,nameDiscipline,semester)
VALUES(2 ,'Высшая математика',1 )
INSERT INTO Discipline(ID,nameDiscipline,semester)
VALUES( 3,'Спецглавы математики',5 )
INSERT INTO Discipline(ID,nameDiscipline,semester)
VALUES( 4,'Основы алгоритмизации и программирования',2 )
INSERT INTO Discipline(ID,nameDiscipline,semester)
VALUES( 5,'Алгоритмы и структуры данных',2 )
INSERT INTO Discipline(ID,nameDiscipline,semester)
VALUES( 6,'Казахский язык',1 )
INSERT INTO Discipline(ID,nameDiscipline,semester)
VALUES( 7,'Английский язык', 1)
INSERT INTO Discipline(ID,nameDiscipline,semester)
VALUES( 8,'Криптография',6 )
INSERT INTO Discipline(ID,nameDiscipline,semester)
VALUES( 9,'Информационные основы защиты информации',4 )
INSERT INTO Discipline(ID,nameDiscipline,semester)
VALUES( 10,'Дискретная математика',4 )
INSERT INTO Discipline(ID,nameDiscipline,semester)
VALUES( 11,'Философия',3 )
INSERT INTO Discipline(ID,nameDiscipline,semester)
VALUES( 12,'Политология',4 )
INSERT INTO Discipline(ID,nameDiscipline,semester)
VALUES(13 ,'ООП Java',4 )
INSERT INTO Discipline(ID,nameDiscipline,semester)
VALUES( 14,'Основы права и антикоррупционной культуры',5 )
INSERT INTO Discipline(ID,nameDiscipline,semester)
VALUES( 15,'Системы управления базами данных',6 )
INSERT INTO Discipline(ID,nameDiscipline,semester)
VALUES( 16,'Менеджент баз данных',7 )
INSERT INTO Discipline(ID,nameDiscipline,semester)
VALUES( 17,'учебная практика',2 )
INSERT INTO Discipline(ID,nameDiscipline,semester)
VALUES( 18,'преддипломная практика',8 )
INSERT INTO Discipline(ID,nameDiscipline,semester)
VALUES( 19,'Разработка веб приложения',8 )
INSERT INTO Discipline(ID,nameDiscipline,semester)
VALUES( 20,'Зеленая энергетика',7 )